# Generated by Django 5.1.4 on 2025-01-16 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d1fe1448-4cd7-4f3a-b972-51bcf584dd10'), editable=False, primary_key=True, serialize=False)),
                ('right', models.BooleanField(default=False)),
            ],
        ),
    ]
