# Generated by Django 5.1.4 on 2025-01-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('right', models.BooleanField(default=False)),
            ],
        ),
    ]
