# Generated by Django 5.1.5 on 2025-01-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('codename', models.CharField(editable=False, max_length=30)),
                ('name', models.CharField(editable=False, max_length=30)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='admin_permission_set', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='RightPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.permission')),
            ],
            options={
                'db_table': 'admin_right_permissions',
            },
        ),
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('permissions', models.ManyToManyField(through='admin.RightPermission', to='admin.permission')),
            ],
        ),
        migrations.AddField(
            model_name='rightpermission',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.rights'),
        ),
    ]
