# Generated by Django 5.1.5 on 2025-01-20 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True,
                                   serialize=False),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True,
                                           serialize=False)),
                ('codename', models.CharField(editable=False, max_length=30)),
                ('name', models.CharField(editable=False, max_length=30)),
                ('content_type', models.ForeignKey(editable=False,
                                                   on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='admin_premission_set',
                                                   to='contenttypes.contenttype')),
            ],
        ),
    ]
