# Generated by Django 5.1.4 on 2025-01-10 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b836712-7b52-4b3b-9487-00c8a03ecabc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
