# Generated by Django 5.1.4 on 2025-01-13 14:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('11f939a5-0293-4d7e-8af7-47b4654861f4'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
