# Generated by Django 5.1.5 on 2025-01-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0002_alter_rights_id_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.AutoField(editable=False, primary_key=True,
                                   serialize=False),
        ),
        migrations.AlterField(
            model_name='rights',
            name='id',
            field=models.AutoField(editable=False, primary_key=True,
                                   serialize=False),
        ),
    ]
