# Generated by Django 5.1.4 on 2025-01-10 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('faa374fd-308b-453c-a7b7-48bbd854704a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
