# Generated by Django 5.1.4 on 2025-01-14 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('da169c57-fe69-414e-b0bf-da2637696393'), editable=False, primary_key=True, serialize=False),
        ),
    ]
