# Generated by Django 5.1.4 on 2025-01-14 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0002_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('6ff09b7e-c8fb-43cb-acdb-036db5205bf4'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
