# Generated by Django 5.1.5 on 2025-01-20 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0003_alter_permission_id_alter_rights_id'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='content_type',
            field=models.ForeignKey(editable=False,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='admin_permission_set',
                                    to='contenttypes.contenttype'),
        ),
    ]
