# Generated by Django 5.1.4 on 2025-01-14 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0003_alter_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.UUID('4a302932-af3c-4eb4-bd67-5fa4967fadb8'),
                    editable=False, primary_key=True, serialize=False)),
                ('right', models.BooleanField(default=False)),
            ],
        ),
    ]
