# Generated by Django 5.1.5 on 2025-01-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0004_alter_permission_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rights',
            name='right',
        ),
        migrations.AddField(
            model_name='rights',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rights',
            name='permissions',
            field=models.ManyToManyField(to='admin.permission'),
        ),
    ]
