# Generated by Django 5.1.5 on 2025-01-20 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0005_remove_rights_right_rights_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rights',
            name='permissions',
        ),
        migrations.CreateModel(
            name='RightPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('permission',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='admin.permission')),
                ('right',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='admin.rights')),
            ],
            options={
                'db_table': 'admin_right_permissions',
            },
        ),
    ]
