# Generated by Django 5.1.4 on 2025-01-14 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0005_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('5afdde7f-5e57-4bd3-8a97-db44745d9130'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
