# Generated by Django 5.1.4 on 2025-01-15 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0006_alter_rights_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('f7516ab1-6648-41b3-8c66-c1db0970cd61'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
