# Generated by Django 5.1.5 on 2025-01-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0006_remove_rights_permissions_rightpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='rights',
            name='permissions',
            field=models.ManyToManyField(through='admin.RightPermission',
                                         to='admin.permission'),
        ),
    ]
