# Generated by Django 5.1.4 on 2025-01-15 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0007_alter_rights_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('0f2875b0-2529-4af9-960a-f56c3845d3b0'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
