# Generated by Django 5.1.4 on 2025-01-15 15:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0008_alter_rights_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('a680da9b-bf1a-403b-be50-ec97167b76d8'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
