# Generated by Django 5.1.5 on 2025-01-17 15:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0009_alter_rights_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('dcaa7e6d-03b8-4d24-ad93-1c2865e991f1'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
