# Generated by Django 5.1.5 on 2025-01-17 15:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0010_alter_rights_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('8df7ed0c-ba32-41d7-826b-a2371ed342a3'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
