# Generated by Django 5.1.5 on 2025-01-17 15:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0011_alter_rights_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('d85b9096-6b47-4fe8-8d27-55690d1d23ed'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
