# Generated by Django 5.1.5 on 2025-01-17 16:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0012_alter_rights_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('970fa73f-6250-4faf-8707-a359ebfbfe97'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
