# Generated by Django 5.1.4 on 2025-01-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('email', models.EmailField(default='default@default.fr', max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(default='default', max_length=15)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_picture/')),
            ],
        ),
    ]
