# Generated by Django 5.1.4 on 2025-01-15 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('07fb3b60-16a7-4247-9276-de23c0d37ad2'),
                editable=False),
        ),
    ]
