# Generated by Django 5.1.4 on 2025-01-15 15:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0002_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('d330514a-48c7-4ac8-a233-ecdd6192e1a7'),
                editable=False),
        ),
    ]
