# Generated by Django 5.1.5 on 2025-01-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account',
         '0002_alter_profile_first_name_alter_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default', null=True,
                                    upload_to='profile/'),
        ),
    ]
