# Generated by Django 5.1.5 on 2025-01-17 15:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('fc179b75-5419-4f33-9682-7d00a862b166'),
                editable=False),
        ),
    ]
