# Generated by Django 5.1.5 on 2025-01-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile/default.png', null=True,
                                    upload_to='profile/'),
        ),
    ]
