# Generated by Django 5.1.5 on 2025-01-17 15:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('08658647-34a4-48bd-9043-933e14ec4bc4'),
                editable=False),
        ),
    ]
