# Generated by Django 5.1.5 on 2025-01-17 15:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0005_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('dba90935-5a93-45d3-af07-a03227e93b97'),
                editable=False),
        ),
    ]
