# Generated by Django 5.1.5 on 2025-01-17 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0006_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
    ]
