version: '3.8'

services:
  django-web:
    image: ${{ env.REGISTRY }}/${{ env.OWNER }}/django-web:latest
    build: null  # Désactive complètement la directive "build"

  nginx:
    image: ${{ env.REGISTRY }}/${{ env.OWNER }}/nginx:latest
    build: null  # Désactive complètement la directive "build"
