services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - wp-networks
  
  django-web:
    depends_on:
      - db
    expose:
      - 8000
    build: .
    volumes:
      - ./static:/app/staticfiles
    env_file:
      - .env

  nginx:
    image: nginx
    ports: 
      - "8001:80" #"HOST_PORT:CONTAINER_PORT"
    depends_on:
      - django-web
    build: ./nginx
    env_file: .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    networks:
      - wp-networks

networks:
  wp-networks:
    driver: bridge

volumes:
  postgres_data:

#   wordpress:
#     build: ./requirements/wordpress
#     image: wordpress
#     env_file: .env
#     volumes:
#       - wordpress:/var/www/html
#     depends_on:
#       - mariadb
#       - redis
#     expose:
#       - "9000"
#     networks:
#       - wp-networks

#   mariadb:
#     build: ./requirements/mariadb
#     env_file: .env
#     image: mariadb
#     volumes:
#       - mariadb:/var/lib/mysql
#     restart: always
#     expose: 
#       - 3306
#     ports:
#       - "3306:3306"
#     networks:
#       - wp-networks
  
#   redis:
#     build: ./requirements/bonus/redis
#     image: redis
#     restart: always
#     ports:
#       - '6379:6379'
#     expose:
#       - '6379'
#     networks:
#       - wp-networks

# volumes:
#   mariadb:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/bpoyet/data/mariadb

#   wordpress:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/bpoyet/data/wordpress
#   weather:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/bpoyet/data/weather
