# Generated by Django 5.1.7 on 2025-03-21 14:10

import datetime

import django.utils.timezone
from django.db import migrations, models

import utils.util


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('game', '0006_alter_game_loser_alter_game_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id',
                 models.IntegerField(default=utils.util.create_tournament_id,
                                     editable=False, primary_key=True,
                                     serialize=False, unique=True)),
                ('created_at',
                 models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('CREATING', 'creating'), (
                'MATCHMAKING', 'matchmaking'), ('STARTING', 'starting'),
                                                     ('RUNNING', 'running'),
                                                     ('ENDING', 'ending'), (
                                                     'DESTROYING',
                                                     'destroying'),
                                                     ('FINISHED', 'finished'),
                                                     ('ERROR', 'error')],
                                            default='creating', max_length=20)),
                ('timer', models.DurationField(default=datetime.timedelta(0),
                                               editable=False, null=True)),
                ('max_players', models.IntegerField(default=8, validators=[
                    utils.util.validate_even])),
                ('scoreboards', models.JSONField(default=list)),
                ('games',
                 models.ManyToManyField(related_name='games', to='game.game')),
            ],
            options={
                'db_table': 'pong_tournaments',
            },
        ),
    ]
