# Generated by Django 5.1.7 on 2025-03-26 16:09

import datetime

import django.utils.timezone
from django.db import migrations, models

import utils.util


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.IntegerField(default=utils.util.create_tournament_id, editable=False, primary_key=True,
                                           serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(
                    choices=[('CREATING', 'creating'), ('MATCHMAKING', 'matchmaking'), ('STARTING', 'starting'),
                             ('RUNNING', 'running'), ('ENDING', 'ending'), ('DESTROYING', 'destroying'),
                             ('FINISHED', 'finished'), ('ERROR', 'error')], default='creating', max_length=20)),
                ('timer', models.DurationField(default=datetime.timedelta(0), editable=False, null=True)),
                ('max_players', models.IntegerField(default=8, validators=[utils.util.validate_even])),
                ('scoreboards', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'pong_tournaments',
            },
        ),
    ]
