# Generated by Django 5.1.7 on 2025-04-10 11:47

from django.db import migrations, models

import utils.util


class Migration(migrations.Migration):
    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='id',
            field=models.CharField(default=utils.util.create_tournament_id, editable=False, max_length=5, primary_key=True, serialize=False,
                                   unique=True),
        ),
    ]
