# Generated by Django 5.1.7 on 2025-05-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='code',
            field=models.CharField(default='', editable=False, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
