# Generated by Django 5.1.7 on 2025-05-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='scoreboards',
            field=models.JSONField(blank=True, default={'scoreboards': []}),
        ),
    ]
