# Generated by Django 5.1.7 on 2025-05-19 13:00

import utils.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournaments_scoreboards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='scoreboards',
            field=models.JSONField(blank=True, default=utils.util.default_scoreboards),
        ),
    ]
