# Generated by Django 5.1.7 on 2025-04-15 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0004_create_admin'),
        ('tournaments', '0002_alter_tournaments_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='bots',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.clients'),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='name',
            field=models.TextField(default="<django.db.models.fields.CharField>'s tournaments", max_length=30),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='tournaments_players', to='client.clients'),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='points_to_win',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
