# Generated by Django 5.1.7 on 2025-05-07 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tournaments', '0002_alter_tournaments_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='status',
        ),
    ]
