# Generated by Django 5.1.7 on 2025-05-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0004_create_admin'),
        ('tournaments', '0003_remove_tournaments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='client.clients'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host', to='client.clients'),
        ),
    ]
