# Generated by Django 5.1.7 on 2025-04-23 13:14

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tournaments', '0003_tournaments_bots_tournaments_host_tournaments_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 23, 13, 14, 9, 393882, tzinfo=datetime.timezone.utc)),
        ),
    ]
