# Generated by Django 5.1.7 on 2025-04-23 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tournaments', '0004_alter_tournaments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
