# Generated by Django 5.1.7 on 2025-04-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tournaments', '0005_alter_tournaments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='status',
            field=models.CharField(
                choices=[('CREATING', 'creating'), ('WAITING', 'waiting'), ('CREATING_MATCH', 'creating_match'), ('STARTING', 'starting'),
                         ('RUNNING', 'running'), ('ENDING', 'ending'), ('DESTROYING', 'destroying'), ('FINISHED', 'finished'), ('ERROR', 'error')],
                default='creating', max_length=20),
        ),
    ]
