# Generated by Django 5.1.7 on 2025-04-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tournaments', '0006_alter_tournaments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='status',
            field=models.CharField(
                choices=[('CREATING', 'creating'), ('WAITING', 'waiting'), ('STARTING', 'starting'), ('RUNNING', 'running'), ('ENDING', 'ending'),
                         ('DESTROYING', 'destroying'), ('FINISHED', 'finished'), ('ERROR', 'error')], default='creating', max_length=20),
        ),
    ]
