global:
  scrape_interval: 5s
rule_files:
  - "/etc/prometheus/recording_rules.yml"
  - "/etc/prometheus/alerting_rules.yml"
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: node
    static_configs:
      - targets:
        - node-exporter:9100
  - job_name: db
    static_configs:
      - targets: ['postgresql-exporter:9187']
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']