apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # If Prometheus is running in a separate container
    isDefault: true
    editable: true