BALL_SPEED = 30
PADDLE_SPEED = 15
PADDLE_WIDTH = 10
PADDLE_HEIGHT = 100
BALL_RADIUS = 1
FPS = 240
OFFSET_PADDLE = 25
CANVAS_WIDTH = 1000
CANVAS_HEIGHT = 500

__all__ = ["BALL_SPEED", "PADDLE_SPEED", "PADDLE_WIDTH", "PADDLE_HEIGHT", "BALL_RADIUS", "FPS", "OFFSET_PADDLE", "CANVAS_WIDTH", "CANVAS_HEIGHT"]