BALL_SPEED = 290
PADDLE_SPEED = 300
PADDLE_WIDTH = 20
PADDLE_HEIGHT = 100
BALL_RADIUS = 1
FPS = 180
OFFSET_PADDLE = 25
CANVAS_WIDTH = 1000
CANVAS_HEIGHT = 500
ANGLE_FACTOR = 3.0
MAX_ANGLE_FACTOR = 0.7
MIN_HORIZONTAL_PERCENT = 0.8
PADDING_PADDLE = 5
PADDING_SCORE = 10
MAX_SPEED = 800
ACCEL = 1.2
# Do not forget to add your Constant here ! otherwise "*" will not see them
__all__ = ["BALL_SPEED", "PADDLE_SPEED", "PADDLE_WIDTH", "PADDLE_HEIGHT", "BALL_RADIUS", "FPS", "OFFSET_PADDLE",
           "CANVAS_WIDTH", "CANVAS_HEIGHT", "ANGLE_FACTOR", "MAX_ANGLE_FACTOR", "MIN_HORIZONTAL_PERCENT", "PADDING_PADDLE",
           "PADDING_SCORE", "MAX_SPEED", "ACCEL"]
