# Generated by Django 5.1.7 on 2025-03-31 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('client',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.clients')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.game')),
            ],
            options={
                'db_table': 'pong_players',
            },
        ),
    ]
