# Generated by Django 5.1.7 on 2025-03-26 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_game', models.IntegerField(blank=True, default=0)),
                ('wins', models.IntegerField(blank=True, default=0)),
                ('losses', models.IntegerField(blank=True, default=0)),
                ('mmr', models.IntegerField(blank=True, default=50)),
                ('rank', models.CharField(blank=True, default='bronze', max_length=100)),
            ],
            options={
                'db_table': 'players_stats',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.clients')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.game')),
            ],
            options={
                'db_table': 'pong_players',
            },
        ),
    ]
