# Generated by Django 5.1.7 on 2025-05-12 12:14

import django.db.models.deletion
from django.db import migrations, models

import apps.player.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('mmr_change', models.IntegerField(default=0)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.clients')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.game')),
            ],
            options={
                'db_table': 'pong_players',
            },
            bases=(models.Model, apps.player.models.PlayerRuntime),
        ),
    ]
