# Generated by Django 5.1.6 on 2025-03-03 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='rank',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pong.rank'),
        ),
    ]
