# Generated by Django 5.1.7 on 2025-05-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mmr_change',
            field=models.IntegerField(default=0),
        ),
    ]
