# Generated by Django 5.1.7 on 2025-04-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
