# Generated by Django 5.1.6 on 2025-03-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_playerstats_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='rank',
            field=models.CharField(blank=True, default='bronze', max_length=100),
        ),
    ]
