# Generated by Django 5.1.7 on 2025-05-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0001_initial'),
        ('authentification', '0001_initial'),
        ('client', '0001_initial'),
        ('notifications', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.friend'),
        ),
        migrations.AddField(
            model_name='clients',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.password'),
        ),
        migrations.AddField(
            model_name='clients',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.profile'),
        ),
        migrations.AddField(
            model_name='clients',
            name='rights',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.rights'),
        ),
        migrations.AddField(
            model_name='clients',
            name='twoFa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.twofa'),
        ),
    ]
