# Generated by Django 5.1.7 on 2025-05-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('client', '0002_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='games',
            field=models.ManyToManyField(blank=True, to='game.game'),
        ),
        migrations.AddField(
            model_name='clients',
            name='stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.stats'),
        ),
    ]
