# Generated by Django 5.1.7 on 2025-03-31 13:20
from django.conf import settings
from django.db import migrations
from django.db.migrations.exceptions import IrreversibleError

from utils.util import format_validation_errors


def create_admin(apps, schema_editor):
    Clients = apps.get_model('client', 'Clients')
    from utils.serializers.client import ClientSerializer

    if not Clients.objects.filter(profile__email=settings.ADMIN_EMAIL).exists():
        data = {
            'profile': {
                'first_name': 'admin',
                'last_name': 'transcendence',
                'email': settings.ADMIN_EMAIL,
                'username': settings.ADMIN_USERNAME
            },
            'password': {
                'password': settings.ADMIN_PWD,
            },
            'is_admin': True
        }

        serializer = ClientSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
        else:
            raise IrreversibleError(f'Failed to create admin in migration file: '
                                    f'{format_validation_errors(serializer.errors)}')


def remove_client(apps, schema_editor):
    Clients = apps.get_model('client', 'Clients')
    Clients.objects.delete(profile_email=settings.ADMIN_EMAIL)


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0003_clients_friend'),
    ]

    operations = [
        migrations.RunPython(create_admin, remove_client)
    ]
