# Generated by Django 5.1.7 on 2025-05-02 02:24

from django.db import migrations
from django.conf import settings
from django.db.migrations.exceptions import IrreversibleError
from utils.util import format_validation_errors

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.client.migrations.0004_create_admin

def create_admin(apps, schema_editor):
    Clients = apps.get_model('client', 'Clients')
    from utils.serializers.client import ClientSerializer

    if not Clients.objects.filter(profile__email=settings.ADMIN_EMAIL).exists():
        data = {
            'profile': {
                'first_name': 'admin',
                'last_name': 'transcendence',
                'email': settings.ADMIN_EMAIL,
                'username': settings.ADMIN_USERNAME
            },
            'password': {
                'password': settings.ADMIN_PWD,
                'passwordcheck': settings.ADMIN_PWD
            }
        }

        serializer = ClientSerializer(data=data, context={'is_admin': True})
        if serializer.is_valid():
            serializer.save()
        else:
            raise IrreversibleError(f'Failed to create admin in migration file: '
                                    f'{format_validation_errors(serializer.errors)}')


def remove_client(apps, schema_editor):
    Clients = apps.get_model('client', 'Clients')
    Clients.objects.delete(profile_email=settings.ADMIN_EMAIL)
    
class Migration(migrations.Migration):

    replaces = [('client', '0004_create_admin'), ('client', '0005_remove_stats_rank')]

    dependencies = [
        ('client', '0003_clients_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='rank',
        ),
        migrations.RunPython(create_admin, remove_client),
    ]

