# Generated by Django 5.1.7 on 2025-05-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_create_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='rank',
        ),
    ]
