# Generated by Django 5.1.7 on 2025-05-06 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_clients_profile'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile'),
        ),
    ]
