# Generated by Django 5.1.4 on 2024-12-16 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_alter_user_id_alter_user_session_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('14e073ee-5761-480e-af12-24f2e9c8b010'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_user',
            field=models.UUIDField(default=uuid.UUID('bcd838a2-04d7-4e72-aca1-7241bf89ef07')),
        ),
    ]
