# Generated by Django 5.1.7 on 2025-03-28 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0001_initial'),
        ('authentification', '0001_initial'),
        ('game', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_game', models.IntegerField(blank=True, default=0)),
                ('wins', models.IntegerField(blank=True, default=0)),
                ('losses', models.IntegerField(blank=True, default=0)),
                ('mmr', models.IntegerField(blank=True, default=50)),
                ('rank', models.CharField(blank=True, default='bronze', max_length=100)),
                ('games', models.ManyToManyField(blank=True, to='game.game')),
            ],
            options={
                'db_table': 'client_stats',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.password')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile')),
                ('rights', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.rights')),
                ('twoFa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.twofa')),
                ('stats', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.stats')),
            ],
            options={
                'db_table': 'client_list',
            },
        ),
    ]
