# Generated by Django 5.1.6 on 2025-02-28 17:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('admin', '0001_initial'),
        ('authentification', '0001_initial'),
        ('player', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.password')),
                ('player',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile')),
                (
                'rights', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.rights')),
                ('twoFa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.twofa')),
            ],
            options={
                'db_table': 'client_list',
            },
        ),
    ]
