# Generated by Django 5.1.7 on 2025-03-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_friend_delete_friendrequest'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='friendrequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.friend'),
        ),
    ]
