# Generated by Django 5.1.7 on 2025-04-08 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_friend_email'),
        ('shared', '0002_clients_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='friendrequest',
        ),
        migrations.AddField(
            model_name='clients',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.friend'),
        ),
    ]
