# Generated by Django 5.1.5 on 2025-01-27 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_alter_profile_profile_picture'),
        ('admin', '0001_initial'),
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_auth.password')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('rights', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.rights')),
                ('twoFa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_auth.twofa')),
            ],
        ),
    ]
