# Generated by Django 5.1.4 on 2025-01-16 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('admin', '0001_initial'),
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.UUID('cf3dc8a6-1a15-4e48-a881-ad1b787de3ca'),
                    editable=False, primary_key=True, serialize=False)),
                ('admin', models.ForeignKey(null=True,
                                            on_delete=django.db.models.deletion.CASCADE,
                                            to='admin.admin')),
                ('auth', models.ForeignKey(default=1,
                                           on_delete=django.db.models.deletion.CASCADE,
                                           to='my_auth.auth')),
                ('profile', models.ForeignKey(default=1,
                                              on_delete=django.db.models.deletion.CASCADE,
                                              to='account.profile')),
            ],
        ),
    ]
