# Generated by Django 5.1.5 on 2025-01-21 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0005_alter_profile_profile_picture'),
        ('my_auth', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='my_auth.password'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='account.profile'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='twoFa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='my_auth.twofa'),
        ),
    ]
