# Generated by Django 5.1.4 on 2024-12-13 14:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_user_id_alter_user_session_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a22a00ea-7b51-4da6-b096-ec5d8aa8f3d5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_user',
            field=models.UUIDField(default=uuid.UUID('41276959-c45d-45d7-8325-3a4076ba00fb')),
        ),
    ]
