# Generated by Django 5.1.4 on 2024-12-16 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_alter_user_id_alter_user_session_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('45c582f6-871b-4699-ad00-54e44b5b1f2e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_user',
            field=models.UUIDField(default=uuid.UUID('c64fa9a8-c576-4c0d-8b14-b7a7f012ff11')),
        ),
    ]
