# Generated by Django 5.1.4 on 2025-01-07 12:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_alter_user_id_alter_user_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.TextField(default='heyyyy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8b8e3d1f-a5e3-4f9e-a083-64e578140f30'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_user',
            field=models.UUIDField(default=uuid.UUID('4a8f33f4-8fc7-42b6-adf3-3bac19d4a760')),
        ),
    ]
