# Generated by Django 5.1.4 on 2025-01-07 12:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_user_test_alter_user_id_alter_user_session_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64a7043d-293f-4f17-b5c4-a618f0cfa211'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_user',
            field=models.UUIDField(default=uuid.UUID('d92fdc64-f025-4b54-89e7-574130658df6')),
        ),
    ]
