# Generated by Django 5.1.4 on 2025-01-13 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_remove_user_test_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4e2fd6b8-7631-4585-bbc9-557580f89f2e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_user',
            field=models.UUIDField(default=uuid.UUID('602ccf8e-adfa-46de-860b-08e196cdcb73')),
        ),
    ]
