# Generated by Django 5.1.4 on 2025-01-14 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('admin', '0003_alter_admin_id'),
        ('auth', '0013_alter_auth_id_alter_auth_session_user'),
        ('shared', '0009_remove_user_test_alter_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.UUID('6981e525-05d3-4684-9ccb-339ebbe1aaa9'),
                    editable=False, primary_key=True, serialize=False)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.admin')),
                ('auth', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.auth')),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
