# Generated by Django 5.1.4 on 2025-01-10 15:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_remove_user_test_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f09a7766-51ff-4be5-ab2e-2cd1edc36b93'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_user',
            field=models.UUIDField(default=uuid.UUID('0f9a99b9-0119-48e7-ac29-f351bca81ac6')),
        ),
    ]
