# Generated by Django 5.1.4 on 2025-01-13 14:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('admin', '0002_alter_admin_id'),
        ('auth', '0012_remove_auth_first_name_auth_password_and_more'),
        ('shared', '0009_remove_user_test_alter_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.UUID('664e0e1f-73fb-4f7f-9f8b-66677ab1faed'),
                    editable=False, primary_key=True, serialize=False)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.admin')),
                ('auth', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.auth')),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
