# Generated by Django 5.1.4 on 2025-01-10 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('admin', '0003_alter_admin_id'),
        ('auth', '0015_alter_auth_id_alter_auth_session_user'),
        ('shared', '0009_remove_user_test_alter_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('350ed45e-6888-4813-8adc-6d0bc63570d5'), editable=False, primary_key=True, serialize=False)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.admin')),
                ('auth', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.auth')),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
