# Generated by Django 5.1.4 on 2025-01-14 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_client_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.UUID('47fbe4ff-6d6b-4cae-9f9e-25cb38f0d517'), editable=False, primary_key=True, serialize=False),
        ),
    ]
