# Generated by Django 5.1.4 on 2025-01-14 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0001_initial'),
        ('admin', '0004_rights'),
        ('auth', '0014_password'),
        ('shared', '0010_client_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.UUID('352bea60-d8f7-4919-b0c0-63cd62ab03b7'),
                    editable=False, primary_key=True, serialize=False)),
                ('password', models.ForeignKey(default=1,
                                               on_delete=django.db.models.deletion.CASCADE,
                                               to='auth.password')),
                ('profile', models.ForeignKey(default=1,
                                              on_delete=django.db.models.deletion.CASCADE,
                                              to='account.profile')),
                ('rights', models.ForeignKey(null=True,
                                             on_delete=django.db.models.deletion.CASCADE,
                                             to='admin.rights')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
