# Generated by Django 5.1.4 on 2025-01-14 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shared', '0011_clients_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('e53640e9-dd0e-420a-8a66-9b0efaa1b465'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
