# Generated by Django 5.1.4 on 2025-01-15 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shared', '0012_alter_clients_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('be14ee70-c620-43e2-b8f5-0e565c26de3c'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
