# Generated by Django 5.1.4 on 2025-01-15 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shared', '0013_alter_clients_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('32a51914-a0e0-4113-89f3-8c82b436c57b'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
