# Generated by Django 5.1.4 on 2025-01-15 15:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shared', '0014_alter_clients_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('673c3493-a6fd-4b1f-84a5-803a408ecebb'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
