# Generated by Django 5.1.5 on 2025-01-17 15:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shared', '0015_alter_clients_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('74eed6a6-c21f-4d87-91c6-4bf0b1aa0443'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
