# Generated by Django 5.1.5 on 2025-01-17 15:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0022_alter_password_id_alter_twofa_key'),
        ('shared', '0016_alter_clients_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='twoFa',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='auth.twofa'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('e5d199a0-e4dc-4668-86d1-176917af3d99'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
