# Generated by Django 5.1.5 on 2025-01-17 15:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shared', '0017_clients_twofa_alter_clients_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('822bed27-fb5d-4ad7-bb40-b050fe31933a'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
