# Generated by Django 5.1.5 on 2025-01-17 16:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shared', '0019_alter_clients_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   primary_key=True, serialize=False),
        ),
    ]
