# Generated by Django 5.1.4 on 2024-12-12 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_alter_user_id_alter_user_session_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('40ffbd03-f111-4833-b516-fcd35529d502'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_user',
            field=models.UUIDField(default=uuid.UUID('ad5abb5a-2140-44e3-9977-4e355c1afab8')),
        ),
    ]
