# Generated by Django 5.1.7 on 2025-05-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('profile_picture', models.ImageField(default='profile/default.png', null=True, upload_to='profile/')),
                ('coalition', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'client_profile',
            },
        ),
    ]
