# Generated by Django 5.1.7 on 2025-05-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='../static/assets/imgs/profile/default.png', null=True, upload_to='profile/'),
        ),
    ]
