# Generated by Django 5.1.7 on 2025-05-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coalition',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
