# Generated by Django 5.1.7 on 2025-05-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_coalition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='coalition',
        ),
    ]
