"""
Django settings for Transcendence project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""


import os
import sys
from pathlib import Path

import environ

BASE_DIR = Path(__file__).resolve().parent.parent
ENV = environ.Env(DEBUG_MODE=True)
ENV.read_env(env_file=os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ENV('DJANGO_SECRET_KEY')

# JWT Settings
JWT_SECRET_KEY = ENV('JWT_SECRET_KEY')
JWT_EXP_ACCESS_TOKEN = ENV('JWT_EXP_ACCESS_TOKEN', default=30)  # 30 minutes
JWT_EXP_REFRESH_TOKEN = ENV('JWT_EXP_REFRESH_TOKEN', default=30)  # 30 days
JWT_ALGORITH = 'HS256'
PROTECTED_PATHS = [
    '/*'
]
EXCLUDED_PATHS = [
    '/api/auth/login',
    '/api/auth/register',
    '/auth/login',
    '/auth/register',
]
ROLE_PROTECTED_PATHS = {
    '/admin/*': ['admin']
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENV('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1'
]

# Application definition

INSTALLED_APPS = [
    'pong.apps.PongConfig',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'index.apps.IndexConfig',
    'auth.apps.AuthConfig',
    'componentBuilder.apps.ComponentbuilderConfig',
    'account.apps.AccountConfig',
    'shared.apps.SharedConfig',
    'error.apps.ErrorConfig',
    'admin.apps.AdminConfig',
    'api.apps.ApiConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'middleware.middleware.JWTMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Transcendence.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Transcendence.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'transcendence.sqlite3',
        'TEST': {
            'NAME': BASE_DIR / 'test_db.sqlite3',
        },
    }
}

if 'test' in sys.argv:
    DATABASES['default']['NAME'] = BASE_DIR / 'test_db.sqlite3'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Media
MEDIA_URL = '/media/' #Url publique pour acceder au media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#Env variables
USERNAME_LENGHT = ENV('USERNAME_LENGHT', default=15)
FIRSTNAME_LENGHT = ENV('FIRSTNAME_LENGHT', default=50)
LASTNAME_LENGHT = ENV('LASTNAME_LENGHT', default=50)
