# Generated by Django 5.1.7 on 2025-03-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('grafana_token', models.CharField(blank=True, max_length=100, null=True)),
                ('grafana_id', models.IntegerField(default=0)),
                ('grafana_dashboard', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'client_rights',
            },
        ),
    ]
