# Generated by Django 5.1.6 on 2025-02-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'client_rights',
            },
        ),
    ]
