# Generated by Django 5.1.7 on 2025-03-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rights',
            name='grafana_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rights',
            name='grafana_token',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
