# Generated by Django 5.1.7 on 2025-03-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0002_rights_grafana_id_rights_grafana_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='grafana_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
