# Generated by Django 5.1.7 on 2025-03-24 12:58

from django.db import migrations
from django.conf import settings
from django.db import transaction
from utils.websockets.services.chat import uuid_global_room

def create_admin_client(apps, schema_editor):
    # Get model classes as they existed at the time of this migration
    Profile = apps.get_model('profile', 'Profile')
    Password = apps.get_model('authentification', 'Password')
    PlayerStats = apps.get_model('player', 'PlayerStats')
    Player = apps.get_model('player', 'Player')
    TwoFA = apps.get_model('authentification', 'TwoFA')
    Rights = apps.get_model('admin', 'Rights')
    Clients = apps.get_model('shared', 'Clients')
    Rooms = apps.get_model('chat', 'Rooms')

    # Check if admin client already exists
    Clients = apps.get_model('shared', 'Clients')
    existing_admin = Clients.objects.filter(profile__email=settings.ADMIN_EMAIL).first()
    
    if existing_admin is None:
        with transaction.atomic():
            # Create associated models
            profile = Profile.objects.create(
                email=settings.ADMIN_EMAIL, 
                username=settings.ADMIN_USERNAME
            )
            password = Password.objects.create(password=settings.ADMIN_PWD)
            stats = PlayerStats.objects.create()
            player = Player.objects.create(
                nickname=settings.ADMIN_USERNAME, 
                stats=stats
            )
            two_fa = TwoFA.objects.create()
            right = Rights.objects.create(is_admin=True)
            
            # Create admin client
            admin_client = Clients.objects.create(
                profile=profile, 
                password=password, 
                twoFa=two_fa, 
                rights=right,
                player=player
            )
            
            # Set admin for global room
            global_room = Rooms.objects.get(id=uuid_global_room)
            global_room.admin = admin_client
            global_room.save()

def delete_admin_client(apps, schema_editor):
    # Optional: Clean up the admin client if needed
    Clients = apps.get_model('shared', 'Clients')
    Clients.objects.filter(profile__email=settings.ADMIN_EMAIL).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('chat', '0001_initial'),
        ('profile', '0001_initial'),
        ('authentification', '0001_initial'),
        ('player', '0001_initial'),
        ('admin', '0004_rights_grafana_dashboard'),
    ]

    operations = [
        migrations.RunPython(create_admin_client, delete_admin_client)
    ]