# Generated by Django 5.1.6 on 2025-02-28 17:41

import uuid

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=512)),
                ('old_password', models.CharField(max_length=521, null=True)),
            ],
            options={
                'db_table': 'client_auth_pwd',
            },
        ),
        migrations.CreateModel(
            name='TwoFA',
            fields=[
                (
                'key', models.CharField(default=pyotp.random_base32, max_length=32, primary_key=True, serialize=False)),
                ('enable', models.BooleanField(default=False)),
                ('scanned', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'client_auth_2fa',
            },
        ),
    ]
