# Generated by Django 5.1.6 on 2025-03-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofa',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='2fa_qrcodes/'),
        ),
    ]
