# Generated by Django 5.1.7 on 2025-04-07 12:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidatedToken',
            fields=[
                ('jti', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exp', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_invalidated_token',
            },
        ),
    ]
