# Generated by Django 5.1.7 on 2025-04-07 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentification', '0002_invalidatedtoken'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invalidatedtoken',
            table='auth_invalidated_tokens',
        ),
    ]
