# Generated by Django 5.1.7 on 2025-05-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_invalidatedtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalidatedtoken',
            name='token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
