# Generated by Django 5.1.7 on 2025-04-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentification', '0003_alter_invalidatedtoken_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidatedtoken',
            name='token',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invalidatedtoken',
            name='type',
            field=models.CharField(choices=[('ACCESS', 'access'), ('REFRESH', 'refresh')], max_length=20, null=True),
        ),
    ]
