# Generated by Django 5.1.6 on 2025-02-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('name', models.CharField(
                    choices=[('BRONZE', 'bronze'), ('SILVER', 'silver'), ('GOLD', 'gold'), ('PLATINE', 'platine'),
                             ('DIAMOND', 'diamond'), ('CHAMPION', 'champion')], editable=False, max_length=15,
                    primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to='rank_icon/')),
                ('mmr_min', models.IntegerField()),
                ('mmr_max', models.IntegerField()),
            ],
            options={
                'db_table': 'ranks_list',
            },
        ),
    ]
