# Generated by Django 5.1.7 on 2025-03-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(
                choices=[('BRONZE', 'bronze'), ('SILVER', 'silver'), ('GOLD', 'gold'), ('PLATINUM', 'platinum'),
                         ('DIAMOND', 'diamond'), ('CHAMPION', 'champion')], editable=False, max_length=15,
                primary_key=True, serialize=False),
        ),
    ]
