# Generated by Django 5.1.7 on 2025-03-28 14:14

from django.db import migrations
from utils.pong.enums import Ranks

def create_ranks(apps, schema_editor):
    RanksList = apps.get_model('pong', 'Rank')
    
    mmr = 0
    for r in Ranks:
        RanksList.objects.get_or_create(name=r.name, mmr_min=mmr+1, mmr_max=mmr+100)
        mmr += 100
        
def delete_ranks(apps, schema_editor):
    RanksList = apps.get_model('pong', 'Rank')
    RanksList.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_alter_rank_name'),
    ]

    operations = [
        migrations.RunPython(create_ranks, delete_ranks)
    ]
