# Generated by Django 5.1.4 on 2025-01-16 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('61618163-48cf-4895-9e1d-4164389d3d7d'), editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(default='1234', max_length=512)),
                ('session_user', models.UUIDField(default=uuid.UUID('3e205e27-39ba-4001-b00d-f4e16a2885cb'))),
            ],
        ),
    ]
