# Generated by Django 5.1.5 on 2025-01-17 16:57

import uuid

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TwoFA',
            fields=[
                ('key',
                 models.CharField(default=pyotp.random_base32, max_length=32,
                                  primary_key=True, serialize=False)),
                ('enable', models.BooleanField(default=False)),
                ('scanned', models.BooleanField(default=False)),
            ],
        ),
    ]
