# Generated by Django 5.1.5 on 2025-01-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofa',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='2fa_qrcodes/'),
        ),
    ]
