# Generated by Django 5.1.4 on 2024-12-09 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0003_alter_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fisrt_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f842fc0e-7f6b-451a-ad41-710ae1a388ad'), editable=False, primary_key=True, serialize=False),
        ),
    ]
