# Generated by Django 5.1.4 on 2024-12-11 15:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_user_created_at_user_uptaded_at_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1fb38a92-e547-4fe2-a1da-a6b84f5356c6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_user',
            field=models.UUIDField(default=uuid.UUID('9a9fa74a-b272-4887-8c7a-156d2980a0a7')),
        ),
    ]
