# Generated by Django 5.1.4 on 2024-12-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_id_alter_user_session_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
