# Generated by Django 5.1.4 on 2025-01-10 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='first_name',
        ),
        migrations.AddField(
            model_name='auth',
            name='password',
            field=models.CharField(default='1234', max_length=512),
        ),
        migrations.AddField(
            model_name='auth',
            name='session_user',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
