# Generated by Django 5.1.4 on 2025-01-13 14:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='first_name',
        ),
        migrations.AddField(
            model_name='auth',
            name='password',
            field=models.CharField(default='1234', max_length=512),
        ),
        migrations.AddField(
            model_name='auth',
            name='session_user',
            field=models.UUIDField(
                default=uuid.UUID('deb9f057-c5b1-4691-94d6-74eb3daa8c0f')),
        ),
        migrations.AlterField(
            model_name='auth',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('3b011a06-33b1-4bc4-83ce-06ef85e9ab65'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
