# Generated by Django 5.1.4 on 2025-01-14 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_remove_auth_first_name_auth_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f785b19e-c488-4ab5-be6d-41be83e5ede5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auth',
            name='session_user',
            field=models.UUIDField(default=uuid.UUID('53eef3d9-9557-4607-bf0b-c6d6a5109ab6')),
        ),
    ]
