# Generated by Django 5.1.4 on 2025-01-14 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_remove_auth_first_name_auth_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('83ad455f-4152-4500-ba72-39af88c8512a'),
                editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auth',
            name='session_user',
            field=models.UUIDField(
                default=uuid.UUID('1f78d9d6-5d72-438f-80c9-4e6438a538bd')),
        ),
    ]
