# Generated by Django 5.1.4 on 2025-01-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_remove_auth_first_name_auth_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
