# Generated by Django 5.1.4 on 2025-01-10 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_auth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='id',
            field=models.UUIDField(default=uuid.UUID('96d21c5e-4120-4f3e-a777-c5d277848798'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auth',
            name='session_user',
            field=models.UUIDField(default=uuid.UUID('b9e19fe2-9aa8-4e6b-a50d-637fc501d20c')),
        ),
    ]
