# Generated by Django 5.1.4 on 2025-01-14 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0013_alter_auth_id_alter_auth_session_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.UUID('56ce3407-0882-4aa7-8bb2-ce7ed0a3c306'),
                    editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(default='1234', max_length=512)),
                ('session_user', models.UUIDField(
                    default=uuid.UUID('b7c23d97-276e-49ea-becc-6c88d7899106'))),
            ],
        ),
    ]
