# Generated by Django 5.1.4 on 2025-01-14 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0014_password'),
        ('shared', '0011_clients_delete_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth',
        ),
    ]
