# Generated by Django 5.1.4 on 2025-01-10 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_auth_id_alter_auth_session_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='id',
            field=models.UUIDField(default=uuid.UUID('34ab82df-b874-4917-8f0b-96dd750e4832'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auth',
            name='session_user',
            field=models.UUIDField(default=uuid.UUID('ce3a0e37-5410-4b13-8261-d2a76680cb36')),
        ),
    ]
