# Generated by Django 5.1.4 on 2025-01-14 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0015_delete_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('b3a77890-dab6-4a61-a136-7c7f01a7801b'),
                editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='password',
            name='session_user',
            field=models.UUIDField(
                default=uuid.UUID('b124ace5-560e-44cf-aa4f-49a34d3611b3')),
        ),
    ]
