# Generated by Django 5.1.4 on 2025-01-15 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0016_alter_password_id_alter_password_session_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='session_user',
        ),
        migrations.AlterField(
            model_name='password',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('1e76fc38-02be-4551-bb0a-b8669ff8bb6c'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
