# Generated by Django 5.1.4 on 2025-01-15 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0017_remove_password_session_user_alter_password_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('4be217b0-5ba3-4718-8a6e-3adf9b1d4799'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
