# Generated by Django 5.1.4 on 2025-01-15 15:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0018_alter_password_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('9dfec543-7535-4c0e-80ee-1e2f0de665ac'),
                editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=512),
        ),
    ]
