# Generated by Django 5.1.5 on 2025-01-17 15:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0019_alter_password_id_alter_password_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFA',
            fields=[
                ('key',
                 models.CharField(default='FJJMQKAOO7HJC5F6A7AK26ZLQ4FKEVLK',
                                  max_length=32, primary_key=True,
                                  serialize=False)),
                ('enable', models.BooleanField(default=False)),
                ('scanned', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='password',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('bb75b502-6546-46d3-a0fb-d996dbd19553'),
                editable=False, primary_key=True, serialize=False),
        ),
    ]
