# Generated by Django 5.1.5 on 2025-01-17 15:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0020_twofa_alter_password_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('fcac2faf-f09f-4b06-ae68-8c44c63f7533'),
                editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twofa',
            name='key',
            field=models.CharField(default='OXJ7XOFKARRETZ4NNC3LR3RXL7DP6X3I',
                                   max_length=32, primary_key=True,
                                   serialize=False),
        ),
    ]
