# Generated by Django 5.1.5 on 2025-01-17 15:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0021_alter_password_id_alter_twofa_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('42e33196-7caf-4fce-b9e4-c92e8a18a80d'),
                editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twofa',
            name='key',
            field=models.CharField(default='Y3UUHTUJWKIUVXGQJ33GP4CE4BI2D3EI',
                                   max_length=32, primary_key=True,
                                   serialize=False),
        ),
    ]
