# Generated by Django 5.1.5 on 2025-01-17 15:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0022_alter_password_id_alter_twofa_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('12e5ae21-0c74-4a69-8bfe-5c22eb625cf5'),
                editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twofa',
            name='key',
            field=models.CharField(default='ULE5C7ZTX77IDRO4EPGDHKDR4IRXUVRW',
                                   max_length=32, primary_key=True,
                                   serialize=False),
        ),
    ]
