# Generated by Django 5.1.5 on 2025-01-17 16:26

import uuid

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0023_alter_password_id_alter_twofa_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='id',
            field=models.UUIDField(
                default=uuid.UUID('806321cd-d388-4b21-8a00-35ae653fa80a'),
                editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twofa',
            name='key',
            field=models.CharField(default=pyotp.random_base32, max_length=32,
                                   primary_key=True, serialize=False),
        ),
    ]
