# Generated by Django 5.1.4 on 2024-12-13 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7e456bbf-d43f-4b49-894d-76e5171df6b4'), editable=False, primary_key=True, serialize=False)),
                ('session_user', models.UUIDField(default=uuid.UUID('a0f2407d-4c0a-4e26-b0ed-99decb0900cd'))),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.TextField(default='/img/img.png')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
