groups:
  - name: postgresql_alerts
    rules:
      - alert: UserMaxValue
        expr: postgresql:total_clients{datname="dockerdjango", instance="postgresql-exporter:9187", job="db", relname="client_list", schemaname="public"} > 2
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "Excessive User created"
          description: "Threshold for the max users connected"
