groups:
  - name: Prod-rule-group-1
    rules:
# For finding total memory used
    - record: prod:node_memory:used_gb
      expr: (node_memory_MemTotal_bytes  - node_memory_MemFree_bytes) / 1024 / 1024 / 1024
# For Finding the status of node (up or down)
    - record: prod:up_info:QAteam
      expr: up{Group="QATeam"}

  - name: Test-rule-group-1
    rules:
    - record: test:cpu_seconds_total:avg_idle
      expr: avg without(cpu,mode) (rate(node_cpu_seconds_total{mode="idle", Project="website"}[2m]))
  #retrieve databases data
  - name: postgresql_connection_metrics
    interval: 15s
    rules:
    # Total number of database connections
    - record: postgresql:total_connections
      expr: pg_stat_activity_count

    # Connections by database
    - record: postgresql:connections_by_database
      expr: sum(pg_stat_activity_count) by (datname)

    # Active connections
    - record: postgresql:active_connections
      expr: pg_stat_activity_state_count{state="active"}

    # Idle connections
    - record: postgresql:idle_connections
      expr: pg_stat_activity_state_count{state="idle"}

    # Connections by user
    - record: postgresql:connections_by_user
      expr: sum(pg_stat_activity_count) by (usename)

    # Long-running queries (over 5 minutes)
    - record: postgresql:long_running_queries
      expr: count(pg_stat_activity_query_duration_seconds > 300)

    # Alert-ready metrics
    - record: postgresql:connection_usage_percentage
      expr: pg_stat_activity_count / pg_settings_max_connections * 100