groups:
  - name: postgresql_connection_metrics
    interval: 15s
    rules:
    - record: postgresql:total_connections
      expr: pg_stat_activity_count

    - record: postgresql:connections_by_database
      expr: sum(pg_stat_activity_count) by (datname)

    - record: postgresql:active_connections
      expr: pg_stat_activity_state_count{state="active"}

    - record: postgresql:idle_connections
      expr: pg_stat_activity_state_count{state="idle"}

    - record: postgresql:connections_by_user
      expr: sum(pg_stat_activity_count) by (usename)

    - record: postgresql:total_clients
      expr: pg_stat_user_tables_n_live_tup{relname="client_list", datname="dockerdjango"}