#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_user WHERE usename = '$DATABASE_USERNAME') THEN
            CREATE USER $DATABASE_USERNAME WITH PASSWORD '$DATABASE_PASSWORD';
        END IF;
    END
    \$\$;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $DATABASE_USERNAME;
    \c $POSTGRES_DB
    GRANT ALL ON SCHEMA public TO $DATABASE_USERNAME;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $DATABASE_USERNAME;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $DATABASE_USERNAME;
EOSQL

echo "Database initialization complete!"