name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start application using Makefile
        run: make up &> output.log &

      - name: Wait for application to start
        run: |
          sleep 15  # Give some time for services to start
          cat output.log

      - name: Verify startup messages
        run: |
          if grep -q "Application startup complete" output.log && grep -q "Established new database connection" output.log; then
            echo "✅ Application and database started successfully"
          else
            echo "❌ Startup check failed"
            exit 1
          fi
