name: Transcendence Docker CI

on:
  push:
    branches: [ main, 135-feature-create-githubs-actions ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: Transcendence

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create pip cache directory
      run: mkdir -p ~/.cache/pip

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('docker/django/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Create Docker cache directory
      run: mkdir -p /tmp/.buildx-cache

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('docker-compose.yml') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Write environment variables to .env file
      run: |
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
        echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
        echo "SECRET_FA_KEY=${{ secrets.SECRET_FA_KEY }}" >> .env
        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
        echo "GRAFANA_PASSWORD=${{ secrets.GRAFANA_PASSWORD }}" >> .env
        echo "ADMIN_PWD=${{ secrets.ADMIN_PWD }}" >> .env
        echo "DATABASE_NAME=${{ vars.DATABASE_NAME }}" >> .env
        echo "DATABASE_USERNAME=${{ vars.DATABASE_USERNAME }}" >> .env
        echo "DATABASE_HOST=${{ vars.DATABASE_HOST }}" >> .env
        echo "DATABASE_PORT=${{ vars.DATABASE_PORT }}" >> .env
        echo "JWT_EXP_ACCESS_TOKEN=${{ vars.JWT_EXP_ACCESS_TOKEN }}" >> .env
        echo "JWT_EXP_REFRESH_TOKEN=${{ vars.JWT_EXP_REFRESH_TOKEN }}" >> .env
        echo "REDIS_HOST=${{ vars.REDIS_HOST }}" >> .env
        echo "REDIS_PORT=${{ vars.REDIS_PORT }}" >> .env
        echo "ADMIN_EMAIL=${{ vars.ADMIN_EMAIL }}" >> .env
        echo "ADMIN_USERNAME=${{ vars.ADMIN_USERNAME }}" >> .env

    - name: Build Docker Compose services
      run: docker compose build

    - name: Start Docker Compose services
      run: docker compose up -d

    - name: Wait for Django to be ready
      run: |
        until [ "$(curl -k -s -o /dev/null -w '%{http_code}' https://localhost:8000/)" -eq 200 ]; do
          echo "Waiting for Django to start..."
          sleep 5
        done
        echo "Django is ready!"

    - name: Run Django tests
      run: docker compose exec -T django-web python manage.py test

    - name: Stop containers
      if: always()
      run: docker compose down