# Generated by Django 5.1.7 on 2025-04-08 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('friends', models.ManyToManyField(blank=True, related_name='friend_requests_as_friend', to='client.clients')),
                ('pending_friends', models.ManyToManyField(blank=True, related_name='friend_requests_as_pending', to='client.clients')),
            ],
            options={
                'verbose_name_plural': 'Friend Requests',
            },
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
