# Generated by Django 5.1.7 on 2025-04-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0004_create_admin'),
        ('notifications', '0002_friend_delete_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='pending_duel',
            field=models.ManyToManyField(blank=True, related_name='duel_requests_as_pending', to='client.clients'),
        ),
    ]
