# Generated by Django 5.1.7 on 2025-03-27 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_friendrequest_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='unique_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
