# Generated by Django 5.1.7 on 2025-04-18 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0003_friend_pending_duel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='pending_duel',
        ),
    ]
