# Generated by Django 5.1.7 on 2025-04-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0004_create_admin'),
        ('notifications', '0004_remove_friend_pending_duel'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to='client.clients'),
        ),
    ]
