# Generated by Django 5.1.7 on 2025-03-27 15:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_friendrequest_unique_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='pending_friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
