# Generated by Django 5.1.7 on 2025-05-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_create_admin'),
        ('notifications', '0005_friend_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, db_table='user_blocks', related_name='blocked_by', to='client.clients'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friends',
            field=models.ManyToManyField(blank=True, db_table='user_friends', related_name='friend_requests_as_friend', to='client.clients'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='pending_friends',
            field=models.ManyToManyField(blank=True, db_table='user_pending_requests', related_name='friend_requests_as_pending', to='client.clients'),
        ),
        migrations.AlterModelTable(
            name='friend',
            table='friend_requests',
        ),
    ]
