# Generated by Django 5.1.7 on 2025-03-27 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_remove_friendrequest_unique_identifier_and_more'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('friends', models.ManyToManyField(blank=True, related_name='friend_requests_as_friend', to='shared.clients')),
                ('pending_friends', models.ManyToManyField(blank=True, related_name='friend_requests_as_pending', to='shared.clients')),
            ],
            options={
                'verbose_name_plural': 'Friend Requests',
            },
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
