# Generated by Django 5.1.7 on 2025-05-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_friend_blocked_users_alter_friend_friends_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='friend',
            table=None,
        ),
    ]
