# Generated by Django 5.1.7 on 2025-03-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_friend_delete_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
