# Generated by Django 5.1.6 on 2025-02-28 18:34

import datetime

import django.utils.timezone
from django.db import migrations, models

import utils.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(default=utils.util.create_game_id,
                                           editable=False, primary_key=True,
                                           serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('in_tournament', models.BooleanField(default=False, editable=False)),
                ('status', models.CharField(choices=[('CREATING', 'creating'), ('MATCHMAKING', 'matchmaking'), ('STARTING', 'starting'), ('RUNNING', 'running'), ('ENDING', 'ending'), ('DESTROYING', 'destroying'), ('FINISHED', 'finished'), ('ERROR', 'error')], default='creating', max_length=20)),
                ('timer', models.DurationField(default=datetime.timedelta(0), editable=False, null=True)),
            ],
            options={
                'db_table': 'pong_games',
            },
        ),
    ]
