# Generated by Django 5.1.7 on 2025-05-12 12:14

import django.utils.timezone
from django.db import migrations, models

import apps.game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('code', models.CharField(default='', editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_duel', models.BooleanField(default=False)),
                ('points_to_win', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'pong_games',
            },
            bases=(models.Model, apps.game.models.GameRuntime),
        ),
    ]
