# Generated by Django 5.1.7 on 2025-05-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='local',
            field=models.BooleanField(default=False),
        ),
    ]
