# Generated by Django 5.1.7 on 2025-03-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_loser'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='loser_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='winner_score',
            field=models.IntegerField(default=0),
        ),
    ]
