# Generated by Django 5.1.7 on 2025-03-31 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0003_create_ranks'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rank',
            table='pong_ranks',
        ),
    ]
