# Generated by Django 5.1.7 on 2025-03-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_loser_score_game_winner_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='points_to_win',
            field=models.IntegerField(default=3),
        ),
    ]
