# Generated by Django 5.1.7 on 2025-04-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0004_alter_rank_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(editable=False, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
