# Generated by Django 5.1.7 on 2025-04-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0005_alter_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_duel',
            field=models.BooleanField(default=False),
        ),
    ]
