# Generated by Django 5.1.7 on 2025-05-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0006_game_is_duel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.CharField(default='', editable=False, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
