# Generated by Django 5.1.7 on 2025-05-01 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_is_duel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
