# Generated by Django 5.1.7 on 2025-05-06 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0007_remove_game_id_game_code'),
        ('tournaments', '0002_alter_tournaments_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tournament_id',
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament',
                                    to='tournaments.tournaments'),
        ),
    ]
