# Generated by Django 5.1.7 on 2025-03-31 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='client.clients'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin',
                                    to='client.clients'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='clients',
            field=models.ManyToManyField(related_name='rooms', to='client.clients'),
        ),
        migrations.AddField(
            model_name='messages',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages',
                                    to='chat.rooms'),
        ),
    ]
