# Generated by Django 5.1.7 on 2025-03-24 12:58

from django.db import migrations
from utils.websockets.services.chat import uuid_global_room
from django.conf import settings


def create_global_room(apps, schema_editor):
    Rooms = apps.get_model('chat', 'Rooms')
    Clients = apps.get_model('shared', 'Clients')
    
    global_room = Rooms.objects.create(id=uuid_global_room)

    clients = Clients.objects.all()
    global_room.clients.add(*clients)
        
def delete_global_room(apps, schema_editor):
    Rooms = apps.get_model('chat', 'Rooms')
    Rooms.objects.filter(id=uuid_global_room).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_global_room, delete_global_room)
    ]
