# Generated by Django 5.1.6 on 2025-03-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='users',
            new_name='clients',
        ),
    ]
