# Generated by Django 5.1.7 on 2025-03-24 12:58

from django.db import migrations
from utils.websockets.services.chat import uuid_global_room

def create_global_room(apps, schema_editor):
    Rooms = apps.get_model('chat', 'Rooms')
    global_room = Rooms.objects.create(id=uuid_global_room)

    Clients = apps.get_model('shared', 'Clients')
    clients = Clients.objects.all()
    for client in clients:
        global_room.clients.add(client)
        
def delete_global_room(apps, schema_editor):
    Rooms = apps.get_model('chat', 'Rooms')
    Rooms.objects.delete(id=uuid_global_room)

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_global_room, delete_global_room)
    ]
