# Generated by Django 5.1.6 on 2025-03-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_users_rooms_clients'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_room', to='shared.clients'),
        ),
    ]
