# Generated by Django 5.1.7 on 2025-04-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_create_global_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='block_user',
            field=models.TextField(default=''),
        ),
    ]
