# Generated by Django 5.1.6 on 2025-03-11 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rooms_admin'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='shared.clients'),
        ),
    ]
