# Generated by Django 5.1.7 on 2025-04-26 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0004_messages_block_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='block_user',
        ),
    ]
