# Generated by Django 5.1.6 on 2025-03-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_rooms_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='rooms',
            new_name='room',
        ),
    ]
